name: Flutter Build and Firebase Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get
        
      # setup the firebase-setup2.dart file
      - name: generate firebase_setup2.dart
        env:
          KEYSTRING: ${{secrets.KEYSTRING}}
          AUTHDOMAIN: ${{secrets.AUTHDOMAIN}}
          APPID: ${{secrets.APPID}}
          MESSAGINGSENDERID: ${{secrets.MESSAGINGSENDERID}}
          PROJECTID: ${{secrets.PROJECTID}}
          STORAGEBUCKET: ${{secrets.STORAGEBUCKET}}
          MEASUREMENTID: ${{secrets.MEASUREMENTID}}
          GOOGLECLIENTID: ${{secrets.GOOGLECLIENTID}}
        run: |
          cat <<EOF >lib/constants/firebase_setup2.dart
          String keyString="";
          String encodedApiKey="$KEYSTRING";
          String encodedAuthDomain="$AUTHDOMAIN";
          String encodedAppId="$APPID";
          String encodedMessagingSenderId="$MESSAGINGSENDERID";
          String encodedProjectId="$PROJECTID";
          String encodedStorageBucket="$STORAGEBUCKET";
          String encodedMeasurementId="$MEASUREMENTID";
          String encodedGoogleClientId="$GOOGLECLIENTID";
          void doDebugEncrypt(){
          //empty
          }
          EOF

      # Step 4: Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # authenticate with firebase
      - name: Authenticate with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase login:ci --token $FIREBASE_TOKEN


      # # Step 6: Deploy to Firebase Hosting
      # - name: Deploy to Firebase Hosting
      #   run: firebase deploy --only hosting
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
